version: '3'
services:
  configserver:
    build: 
      context: .
      dockerfile: docker/local.Dockerfile
    ports:
      - '3005:3005'
    volumes:
      - ./src/config-files:/conf.d/
      - ./src/:/go/src/github.com/BlockClusterApp/daemon/src
    environment:
#      KUBE_API_SERVER_URL: 'https://k8s-dev-us-west-2-api.blockcluster.io'
#      KUBE_TOKEN: 'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJibG9ja2NsdXN0ZXIiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoiYmxvY2tjbHVzdGVyLWFnZW50LXRva2VuLTRodGo1Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6ImJsb2NrY2x1c3Rlci1hZ2VudCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjU1OWM0ODNmLWQ2ZTQtMTFlOC1iNjVlLTAyYjYzYWIyMDNiZSIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpibG9ja2NsdXN0ZXI6YmxvY2tjbHVzdGVyLWFnZW50In0.tvjvyHBGO40rqK2AbUW7aqsrZtrj_lln4JSlMYpJHapsriNxuEf_8szinwe1N9QxjaxYZtMBdpniouwuC-7H3FKi9zAXm8rrw6fRGLGQ7BbzyWjFjAac9yK1lTdKyy-qECGXfkWZ-eSL2LPfrhtISbydGH815YAcRNl2t7cbPoZ9aO43cU9u7O49FfXgA9yxTIhGtPLQ2ST-yfQYWkjZgGH39ZkQPQMUsjqx7SMKNECAG7y2BLhDb0j40jHTbJ0x3CW3FTI79NogrJwA3OeUiLfQVSZ4LL6veHDdEJN3QqGDAaeD2136NZweaGhEe-cxd1cmRtI5UkJJBCznuY3U7w'
      GO_ENV: 'development'
      SHOW_LOGS: "1"
      LICENSE_KEY: ""
      CLUSTER_IDENTIFIER: ""



