version: '3'
services:
  configserver:
    build: 
      context: .
      dockerfile: docker/local.Dockerfile
    ports:
      - '3005:3005'
    volumes:
      - ./src/config-files:/conf.d/
      - ./src/:/go/src/github.com/BlockClusterApp/daemon/src
    environment:
      KUBE_API_SERVER_URL: 'https://k8s-dev-us-west-2-api.blockcluster.io'
      KUBE_API_USER: 'admin'
      KUBE_API_PASS: 'v8qYNAwGkHOWBghtu1GywXbAno5aX3bH'
      GO_ENV: 'development'
      ENTERPRISE_API_URL: 'https://524ffab0.ngrok.io/daemon'
      SHOW_LOGS: "1"
    deploy:
      resources:
        limits:
          memory: 200M
          cpus: '0.1'
        reservations:
          memory: 50M
          cpus: '0.1'


