apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: network-interfacer
  labels:
    name: network-interfacer
    release: network-interfacer
spec:
  template:
    metadata:
      labels:
        name: network-interfacer
        serviceType: support
        podType: critical
    spec:
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: serviceType
                  operator: In
                  values:
                  - server
              topologyKey: kubernetes.io/hostname
      restartPolicy: Always
      containers:
        - name: server
          image: 426852450903.dkr.ecr.ap-south-1.amazonaws.com/k8s-network-interfacer:220520181130
          imagePullPolicy: IfNotPresent
          env:
          - name: NODE_ENV
            value: test
          livenessProbe:
            httpGet:
              path: /ping
              port: 3005
            timeoutSeconds: 1
            periodSeconds: 7
          readinessProbe:
            httpGet:
              path: /ping
              port: 3005
            timeoutSeconds: 1
            periodSeconds: 5
